_target_: src.datamodules.Datamodules_train.ATLAS_v2

cfg:
  name: ATLAS_v2
  path:
    pathBase: ${data_dir}

    IXI:
      IDs: 
        train: 
          - ${data_dir}/Data/splits/IXI_train_fold0.csv
          - ${data_dir}/Data/splits/IXI_train_fold1.csv
          - ${data_dir}/Data/splits/IXI_train_fold2.csv
          - ${data_dir}/Data/splits/IXI_train_fold3.csv
          - ${data_dir}/Data/splits/IXI_train_fold4.csv
        val: 
          - ${data_dir}/Data/splits/IXI_val_fold0.csv
          - ${data_dir}/Data/splits/IXI_val_fold1.csv
          - ${data_dir}/Data/splits/IXI_val_fold2.csv
          - ${data_dir}/Data/splits/IXI_val_fold3.csv
          - ${data_dir}/Data/splits/IXI_val_fold4.csv
        test: ${data_dir}/Data/splits/IXI_test.csv
    Brats21:
      IDs: 
        test: ${data_dir}/Data/splits/Brats21_test.csv
        val: ${data_dir}/Data/splits/Brats21_val.csv
    ATLAS_v2:
      IDs: 
        test: ${data_dir}/Data/splits/ATLAS_v2_test.csv
        val: ${data_dir}/Data/splits/ATLAS_v2_val.csv
  
  imageDim: [160,192,160] # 
  rescaleFactor: 2
  interRes: [8,8,5] #[HxWxD]
  cropMode: 'isotropic'
  spatialDims: 2D
  unisotropic_sampling: True
  sample_set: False

  preLoad: True
  curvatureFlow: True
  percentile: True
  
  pad: True
  permute: False
  # Augmentations
  randomRotate: False
  rotateDegree: 5
  horizontalFlip: False
  randomBrightness: False
  brightnessRange: (0.75,1.25)
  randomContrast: False
  contrastRange: (0.75,1.25)
  
  modelpath: ${data_dir}/Data/pretrained_2D_model/
  num_workers: 4
  batch_size: 32
  lr : 0.0001
  droplast: True

  cold_diff: False

  # Patching
  patched_processing: False
  proc_patch_depth: 16
  proc_patch_size: 16

  # Evaluation
  mode: t1
  resizedEvaluation: True
  testsets: # specify which test sets to evaluate!
  - Datamodules_eval.ATLAS_v2
  - Datamodules_eval.Brats21
  - Datamodules_train.IXI



